(function(){
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
var FALLBACK_IMAGE='https://raw.githubusercontent.com/arranoust/MiraiExt-SkyStream/main/banner.jpg';
function H(x){var h={'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Referer':manifest.baseUrl+'/'};if(x)for(var k in x)h[k]=x[k];return h}
function dec(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'").replace(/&nbsp;/g,' ')}
function abs(u){u=dec(u).trim();if(!u)return'';if(u.indexOf('//')===0)return'https:'+u;if(/^https?:\/\//i.test(u))return u;if(u.charAt(0)==='/')return manifest.baseUrl.replace(/\/$/,'')+u;return manifest.baseUrl.replace(/\/$/,'')+'/'+u.replace(/^\.?\//,'')}
function txt(s){return dec(s).replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
async function html(u,h){var r=await http_get(u,h||H());return r&&typeof r.body==='string'?r.body:''}
function meta(s,p){var r=new RegExp('<meta[^>]+property=["\\\']'+p+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),m=s.match(r);if(!m){r=new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+property=["\\\']'+p+'["\\\']','i');m=s.match(r)}return m?dec(m[1]):''}
function attr(tag,n){var r=new RegExp('(?:^|\\s)'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i'),m=String(tag||'').match(r);return m?m[2]:''}
function directPoster(u){u=abs(u);if(!u)return FALLBACK_IMAGE;try{var x=new URL(u);if(x.hostname==='animeua.club'||x.hostname==='www.animeua.club'){var sep=u.indexOf('?')>=0?'&':'?';return u+sep+'skystream=16-1'}}catch(e){}return u}
function validImage(u){return !!u&&!/no-img|placeholder|logo|avatar|icon/i.test(String(u))}
function imageFromBlock(b){var m=String(b||'').match(/<img\b[^>]*data-src=["']([^"']+)["'][^>]*>/i);if(m&&validImage(m[1]))return directPoster(m[1]);m=String(b||'').match(/<img\b[^>]*(?:data-lazy-src|data-original|src)=["']([^"']+)["'][^>]*>/i);return m&&validImage(m[1])?directPoster(m[1]):FALLBACK_IMAGE}
function detailPoster(s){var block=s.match(/<div[^>]*class=["'][^"']*pmovie__poster[^"']*["'][^>]*>[\s\S]*?<\/div>/i);if(block){var p=imageFromBlock(block[0]);if(p!==FALLBACK_IMAGE)return p}var im=s.match(/<img\b[^>]*data-src=["']([^"']+)["'][^>]*>/ig)||[];for(var i=0;i<im.length;i++){var u=attr(im[i],'data-src');if(validImage(u))return directPoster(u)}var og=meta(s,'og:image');if(validImage(og))return directPoster(og);return FALLBACK_IMAGE}
function cleanTitle(s){s=txt(s);return s.replace(/\s*[\/|–—-]\s*(дивитися|смотреть|аніме онлайн|anime online)[\s\S]*$/i,'').trim()||s}
function statusOf(block,openTag){var s=(String(openTag||'')+' '+String(block||'')).toLowerCase();if(/\bongoing\b|онґоїнґ|онгоінг/.test(s))return'ongoing';if(/\breleased\b|завершен|закінчен/.test(s))return'released';return''}
function cards(s){var out=[],seen={},re=/<a\b[^>]*class=(["\'])[^"\']*\bposter\b[^"\']*\bgrid-item\b[^"\']*\1[^>]*>[\s\S]*?<\/a>/gi,m;while((m=re.exec(s||''))){var b=m[0],ot=b.match(/^<a\b[^>]*>/i),u=abs(ot?attr(ot[0],'href'):''),t=b.match(/<h3\b[^>]*class=(["\'])[^"\']*\bposter__title\b[^"\']*\1[^>]*>([\s\S]*?)<\/h3>/i),title=t?txt(t[2]):txt(attr(ot?ot[0]:'','title')),image=imageFromBlock(b),status=statusOf(b,ot?ot[0]:'');if(!u||!title||seen[u])continue;seen[u]=1;out.push({title:title,url:u,image:image,status:status})}return out}
async function hydrate(list,limit){var out=[],n=limit?Math.min(list.length,limit):list.length;for(var i=0;i<n;i++){var x=list[i];out.push(new MultimediaItem({title:x.title,url:x.url,posterUrl:x.image||FALLBACK_IMAGE,type:'anime'}))}return out}
async function collectPages(basePath,pageCount){var all=[],seen={};for(var p=1;p<=pageCount;p++){try{var path=p===1?basePath:basePath.replace(/\/$/,'')+'/page/'+p+'/',u=abs(path),part=cards(await html(u));if(p>1&&!part.length)break;for(var i=0;i<part.length;i++){var x=part[i];if(!seen[x.url]){seen[x.url]=1;all.push(x)}}}catch(e){}}return all}
async function getHome(cb){try{var data={},main=await collectPages('/',60);if(!main.length)return cb({success:false,error:'AnimeUA: каталог не знайдено.'});data['AnimeUA - весь каталог ('+main.length+')']=await hydrate(main);var ongoing=main.filter(function(x){return x.status==='ongoing'}),released=main.filter(function(x){return x.status==='released'});if(ongoing.length)data['🟢 Онґоїнґ ('+ongoing.length+')']=await hydrate(ongoing);if(released.length)data['✅ Закінчене ('+released.length+')']=await hydrate(released);var filters=[['🎬 Повнометражки','/film/'],['📺 Аніме серіали','/anime/'],['ONA','/ona/'],['OVA','/ova/'],['🥋 Бойові мистецтва','/boivie/'],['🎭 Драма','/drama/'],['🔎 Детектив','/detektiv/'],['👹 Демони','/demons/'],['🗺️ Пригоди','/adventures/'],['🧠 Психологічне','/psih/'],['💕 Романтика','/romantik/'],['🚀 Фантастика','/fantastika/'],['🧙 Фентезі','/fentezi/']];for(var f=0;f<filters.length;f++){try{var spec=filters[f],list=await collectPages(spec[1],3);if(list.length)data[spec[0]]=await hydrate(list)}catch(e){}}cb({success:true,data:data})}catch(e){cb({success:false,error:'AnimeUA getHome: '+String(e)})}}
async function search(q,cb){try{var u=manifest.baseUrl+'/index.php?do=search&subaction=search&search_start=0&full_search=0&result_from=1&story='+encodeURIComponent(q),c=cards(await html(u));if(!c.length){var all=await collectPages('/',60),z=String(q||'').toLowerCase();c=all.filter(function(x){return x.title.toLowerCase().indexOf(z)>=0})}if(!c.length)return cb({success:false,error:'Нічого не знайдено.'});cb({success:true,data:await hydrate(c)})}catch(e){cb({success:false,error:'AnimeUA search: '+String(e)})}}
async function player(s){var f=s.match(/<div[^>]*class=["'][^"']*video-inside[^"']*["'][^>]*>[\s\S]*?<iframe[^>]*(?:data-src|src)=["']([^"']+)["'][^>]*>/i)||s.match(/<iframe[^>]*(?:data-src|src)=["']([^"']+)["'][^>]*>/i);if(!f)return null;var pu=abs(f[1]),ph=await html(pu,{'User-Agent':UA,'Referer':manifest.baseUrl+'/'}),m=ph.match(/new\s+Playerjs\s*\(\s*\{[\s\S]*?file\s*:\s*["'](\[[\s\S]*?\]|https?:\/\/[^"']+)["'][\s\S]*?\}\s*\)/i);return m?dec(m[1]):null}
function flat(n,o,path){path=path||[];if(!n)return;if(Array.isArray(n)){for(var i=0;i<n.length;i++)flat(n[i],o,path);return}if(typeof n!=='object')return;var title=txt(n.title||''),next=path;if(n.folder&&title)next=path.concat([title]);if(n.file){var k=parseInt(String(title).replace(/^Серія\s*/i,''),10),group=path.join(' › ');o.push({title:title,number:isNaN(k)?o.length+1:k,file:dec(n.file),group:group})}if(n.folder)flat(n.folder,o,next)}
function dedupeExact(a){var out=[],seen={};for(var i=0;i<a.length;i++){var x=a[i],key=String(x.number)+'|'+String(x.group||'')+'|'+String(x.file||'');if(seen[key])continue;seen[key]=1;out.push(x)}out.sort(function(x,y){if(x.number!==y.number)return x.number-y.number;return String(x.group||'').localeCompare(String(y.group||''))});return out}
async function load(url,cb){try{var s=await html(url);if(!s)return cb({success:false,error:'AnimeUA: сторінка недоступна.'});var h=s.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i),title=h?cleanTitle(h[1]):cleanTitle(meta(s,'og:title')||'AnimeUA'),poster=detailPoster(s),d=s.match(/<div class=["'][^"']*page__text[^"']*["'][^>]*>([\s\S]*?)<\/div>/i),desc=d?txt(d[1]):'',eps=[],pf=await player(s);if(pf){if(/^https?:\/\//i.test(pf))eps.push(new Episode({name:'Серія 1',url:pf,season:1,episode:1,dubStatus:'dubbed',posterUrl:poster}));else try{var a=[],cfg=JSON.parse(pf);flat(cfg,a,[]);a=dedupeExact(a);for(var i=0;i<a.length;i++){var label=a[i].title||('Серія '+a[i].number);if(a[i].group)label=label+' • '+a[i].group;eps.push(new Episode({name:label,url:a[i].file,season:1,episode:a[i].number,dubStatus:'dubbed',posterUrl:poster}))}}catch(e){}}cb({success:true,data:new MultimediaItem({title:title,url:url,posterUrl:poster,bannerUrl:poster,type:'anime',description:desc,episodes:eps})})}catch(e){cb({success:false,error:'AnimeUA load: '+String(e)})}}
function add(o,u,q){o.push(new StreamResult({url:dec(u),quality:q||'Auto',source:'AnimeUA',headers:{'Referer':manifest.baseUrl+'/','User-Agent':UA}}))}
async function loadStreams(url,cb){try{var o=[],r=dec(String(url||'').trim()),m,re=/\[([^\]]+)\](https?:\/\/[^,\s]+)/g;while((m=re.exec(r))!==null)add(o,m[2],m[1]);if(!o.length&&/^https?:\/\//i.test(r))add(o,r,r.indexOf('.m3u8')>=0?'HLS':'Auto');if(!o.length)return cb({success:false,error:'AnimeUA: відеопотік не знайдено.'});cb({success:true,data:o})}catch(e){cb({success:false,error:'AnimeUA loadStreams: '+String(e)})}}
globalThis.getHome=getHome;globalThis.search=search;globalThis.load=load;globalThis.loadStreams=loadStreams;
}());
