(function(){
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
var DESKTOP_UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/153.0.0.0 Safari/537.36';
var FALLBACK_IMAGE='https://raw.githubusercontent.com/arranoust/MiraiExt-SkyStream/main/banner.jpg';
function H(x){var h={'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Referer':manifest.baseUrl+'/'};if(x)for(var k in x)h[k]=x[k];return h}
function dec(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'").replace(/&nbsp;/g,' ')}
function abs(u){u=dec(u).trim();if(!u)return'';u=u.replace(/\\\//g,'/');if(u.indexOf('//')===0)return'https:'+u;if(/^https?:\/\//i.test(u))return u;if(u.charAt(0)==='/')return manifest.baseUrl.replace(/\/$/,'')+u;return manifest.baseUrl.replace(/\/$/,'')+'/'+u.replace(/^\.?\//,'')}
function txt(s){return dec(s).replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
function detailKey(u){u=abs(u);if(!u)return'';try{var x=new URL(u);if(x.hostname==='animeua.club'||x.hostname==='www.animeua.club'){x.searchParams.set('skystream_plugin','47');return x.toString()}}catch(e){}return u}
async function html(u,h){var r=await http_get(u,h||H());return r&&typeof r.body==='string'?r.body:''}
async function getRaw(u,h){try{var r=await http_get(u,h||{}),b=r&&typeof r.body==='string'?r.body:'';return{body:b,status:r&&((r.statusCode||r.status))||0,error:''}}catch(e){return{body:'',status:0,error:String(e).slice(0,120)}}}
function meta(s,p){var r=new RegExp('<meta[^>]+property=["\\\']'+p+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),m=s.match(r);if(!m){r=new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+property=["\\\']'+p+'["\\\']','i');m=s.match(r)}return m?dec(m[1]):''}
function attr(tag,n){var r=new RegExp('(?:^|\\s)'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i'),m=String(tag||'').match(r);return m?m[2]:''}
function directPoster(u){u=abs(u);if(!u)return FALLBACK_IMAGE;try{var x=new URL(u);if(x.hostname==='animeua.club'||x.hostname==='www.animeua.club'){var sep=u.indexOf('?')>=0?'&':'?';return u+sep+'skystream=47'}}catch(e){}return u}
function validImage(u){return !!u&&!/no-img|placeholder|logo|avatar|icon/i.test(String(u))}
function bestSrcset(tag){var raw=attr(tag,'data-srcset')||attr(tag,'srcset');if(!raw)return'';var parts=raw.split(','),best='',score=-1;for(var i=0;i<parts.length;i++){var z=parts[i].trim().split(/\s+/),u=z[0]||'',d=z[1]||'',n=parseFloat(d)||i;if(/w$/i.test(d))n=parseFloat(d)||n;else if(/x$/i.test(d))n=(parseFloat(d)||1)*1000;if(validImage(u)&&n>=score){best=u;score=n}}return best}
function imageFromBlock(b){var tags=String(b||'').match(/<img\b[^>]*>/ig)||[];for(var i=0;i<tags.length;i++){var hi=bestSrcset(tags[i]);if(hi)return directPoster(hi);var names=['data-original','data-lazy-src','data-src','src'];for(var j=0;j<names.length;j++){var u=attr(tags[i],names[j]);if(validImage(u))return directPoster(u)}}return FALLBACK_IMAGE}
function detailPoster(s){var block=s.match(/<div[^>]*class=["'][^"']*pmovie__poster[^"']*["'][^>]*>[\s\S]*?<\/div>/i);if(block){var p=imageFromBlock(block[0]);if(p!==FALLBACK_IMAGE)return p}var og=meta(s,'og:image');if(validImage(og))return directPoster(og);var tags=s.match(/<img\b[^>]*>/ig)||[];for(var i=0;i<tags.length;i++){var hi=bestSrcset(tags[i]);if(hi)return directPoster(hi)}return FALLBACK_IMAGE}
function detailBanner(s,poster){var og=meta(s,'og:image');if(validImage(og)){var u=directPoster(og);if(u&&u!==poster)return u}var m=s.match(/(?:background-image\s*:\s*url\(|data-bg\s*=\s*["'])(https?:\/\/[^"')\s]+)/i);if(m&&validImage(m[1]))return directPoster(m[1]);return poster}
function cleanTitle(s){s=txt(s);return s.replace(/\s*[\/|–—-]\s*(дивитися|смотреть|аніме онлайн|anime online)[\s\S]*$/i,'').trim()||s}
function statusOf(block,openTag){var s=(String(openTag||'')+' '+String(block||'')).toLowerCase();if(/\bongoing\b|онґоїнґ|онгоінг/.test(s))return'ongoing';if(/\breleased\b|завершен|закінчен/.test(s))return'released';return''}
function cards(s){var out=[],seen={},re=/<a\b[^>]*class=(["\'])[^"\']*\bposter\b[^"\']*\bgrid-item\b[^"\']*\1[^>]*>[\s\S]*?<\/a>/gi,m;while((m=re.exec(s||''))){var b=m[0],ot=b.match(/^<a\b[^>]*>/i),u=detailKey(ot?attr(ot[0],'href'):''),t=b.match(/<h3\b[^>]*class=(["\'])[^"\']*\bposter__title\b[^"\']*\1[^>]*>([\s\S]*?)<\/h3>/i),title=t?txt(t[2]):txt(attr(ot?ot[0]:'','title')),image=imageFromBlock(b),status=statusOf(b,ot?ot[0]:'');if(!u||!title||seen[u])continue;seen[u]=1;out.push({title:title,url:u,image:image,status:status})}return out}
async function hydrate(list,limit){var out=[],n=limit?Math.min(list.length,limit):list.length;for(var i=0;i<n;i++){var x=list[i];out.push(new MultimediaItem({title:x.title,url:x.url,posterUrl:x.image||FALLBACK_IMAGE,type:'anime'}))}return out}
async function collectPages(basePath,pageCount){var all=[],seen={};for(var p=1;p<=pageCount;p++){try{var path=p===1?basePath:basePath.replace(/\/$/,'')+'/page/'+p+'/',u=abs(path),part=cards(await html(u));if(p>1&&!part.length)break;for(var i=0;i<part.length;i++){var x=part[i];if(!seen[x.url]){seen[x.url]=1;all.push(x)}}}catch(e){}}return all}
async function getHome(cb){try{var data={},main=await collectPages('/',2);if(!main.length)return cb({success:false,error:'AnimeUA: каталог не знайдено.'});data['🔥 Нове на AnimeUA']=await hydrate(main,40);var ongoing=main.filter(function(x){return x.status==='ongoing'});if(ongoing.length)data['🟢 Онґоїнґ']=await hydrate(ongoing,30);var filters=[['🎬 Повнометражки','/film/'],['📺 Аніме серіали','/anime/'],['ONA','/ona/'],['OVA','/ova/'],['💕 Романтика','/romantik/'],['🚀 Фантастика','/fantastika/'],['🧙 Фентезі','/fentezi/']];var jobs=[];for(var f=0;f<filters.length;f++)(function(spec){jobs.push((async function(){try{var list=await collectPages(spec[1],1);return list.length?{name:spec[0],items:await hydrate(list,24)}:null}catch(e){return null}})())})(filters[f]);var rows=await Promise.all(jobs);for(var i=0;i<rows.length;i++)if(rows[i])data[rows[i].name]=rows[i].items;cb({success:true,data:data})}catch(e){cb({success:false,error:'AnimeUA getHome: '+String(e)})}}
async function search(q,cb){try{var u=manifest.baseUrl+'/index.php?do=search&subaction=search&search_start=0&full_search=0&result_from=1&story='+encodeURIComponent(q),c=cards(await html(u));if(!c.length){var all=await collectPages('/',8),z=String(q||'').toLowerCase();c=all.filter(function(x){return x.title.toLowerCase().indexOf(z)>=0})}if(!c.length)return cb({success:false,error:'Нічого не знайдено.'});cb({success:true,data:await hydrate(c,50)})}catch(e){cb({success:false,error:'AnimeUA search: '+String(e)})}}
function playerFileValue(ph){var m=/\bfile\s*:/.exec(ph||'');if(!m)return null;var i=m.index+m[0].length,n=ph.length;while(i<n&&/\s/.test(ph.charAt(i)))i++;if(i>=n)return null;var q=ph.charAt(i);if(q==='"'||q==="'"||q==='`'){i++;var out='',esc=false;for(;i<n;i++){var c=ph.charAt(i);if(esc){out+=c;esc=false;continue}if(c==='\\'){esc=true;out+=c;continue}if(c===q)break;out+=c}return dec(out).replace(/\\(["'\/])/g,'$1')}if(q==='['){var start=i,depth=0,str='',esc2=false;for(;i<n;i++){var ch=ph.charAt(i);if(str){if(esc2){esc2=false;continue}if(ch==='\\'){esc2=true;continue}if(ch===str)str='';continue}if(ch==='"'||ch==="'"||ch==='`'){str=ch;continue}if(ch==='[')depth++;else if(ch===']'){depth--;if(depth===0)return dec(ph.slice(start,i+1))}}}var r=ph.slice(i).match(/^(https?:\/\/[^\s,}]+)/i);return r?dec(r[1]):null}
function iframeUrls(s,base){var out=[],seen={},tags=String(s||'').match(/<iframe\b[^>]*>/ig)||[],names=['data-src','src','data-url','data-player','data-frame','data-video'];for(var i=0;i<tags.length;i++)for(var j=0;j<names.length;j++){var raw=attr(tags[i],names[j]);if(!raw||/^(?:about:|javascript:)/i.test(raw))continue;try{var u=new URL(dec(raw),base||manifest.baseUrl+'/').toString();if(u&&u!==(base||'')&&!seen[u]){seen[u]=1;out.push(u)}}catch(e){}}return out}
function usefulPlayer(u){return /ashdi\.vip|uacdn\.online/i.test(String(u||''))}
function uacdnPlayer(u){return /uacdn\.online/i.test(String(u||''))}
function ashdiPlayer(u){return /ashdi\.vip/i.test(String(u||''))}
async function playerBody(u,page){var hs={'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Referer':page||manifest.baseUrl+'/'};return await getRaw(u,hs)}
function uacdnPayload(s){var m=String(s||'').match(/window\.__PLAYER_PAYLOAD__\s*=\s*(\{[\s\S]*?\});/);if(!m)return null;try{return JSON.parse(m[1])}catch(e){return null}}
async function getUacdn(player,page){var r=await playerBody(player,page);return{payload:r.body?uacdnPayload(r.body):null,status:r.status,error:r.error,body:r.body}}
async function getAshdiFile(player,page){var r=await playerBody(player,page),pf=r.body?playerFileValue(r.body):null;return{file:pf,status:r.status,error:r.error,body:r.body}}
function episodeNumber(title,fallback){var s=txt(title||''),m=s.match(/(?:сер(?:ія|ии|ія)?|series?|episode|ep\.?)[^0-9]{0,8}0*(\d{1,3})/i);if(m)return parseInt(m[1],10);var nums=s.match(/\d{1,3}/g);if(nums&&nums.length)return parseInt(nums[nums.length-1],10);return fallback}
function seasonNumber(path,fallback){var s=Array.isArray(path)?path.join(' › '):String(path||''),m=s.match(/(?:сезон|season)[^0-9]{0,8}0*(\d{1,3})/i);if(m)return parseInt(m[1],10);return fallback}
function flat(n,o,path,pos){path=path||[];if(!n)return;if(Array.isArray(n)){for(var i=0;i<n.length;i++)flat(n[i],o,path,i+1);return}if(typeof n!=='object')return;var title=txt(n.title||''),next=path;if(n.folder&&title)next=path.concat([title]);if(n.file){var k=episodeNumber(title,pos==null?1:pos),sn=seasonNumber(path,1),group=path.join(' › ');o.push({title:title,number:k,season:sn,file:dec(n.file),group:group,pos:pos==null?1:pos})}if(n.folder)flat(n.folder,o,next,1)}
function variantScore(x){var s=String((x.group||'')+' '+(x.title||'')).toLowerCase(),v=0;if(/укр|ukr|україн|озвуч|дубляж|dubbed|дуб/.test(s))v+=120;if(/inari|didko|sundragon|sun dragon|робота голосом|рідний голос|ridnyi holos|ashdi|moonanime|togarashi|fanvox|далі буде|ukrainefastdub|aniua|vrdub|jenary|hatoshi|білі джин|48 volts|amanogawa|molfar|adrian zax|melodicvoice|lifecycle|espada/.test(s))v+=90;if(/субтит|subbed|\bsub\b|original|оригінал|japan|jpn|japanese/.test(s))v-=160;return v}
function studioName(x){var s=txt((x.group||'')+' '+(x.title||''));var tests=[[/inari/i,'InariDuB'],[/didko/i,'Didko Studio'],[/sun\s*dragon|sundragon/i,'SunDragon Studio'],[/робота\s+голосом/i,'Робота Голосом'],[/рідний\s+голос|ridnyi\s+holos/i,'Рідний Голос'],[/ashdi/i,'ASHDI'],[/moonanime/i,'MOONANIME'],[/togarashi/i,'Togarashi'],[/fanvox/i,'FanVoxUA'],[/далі\s+буде/i,'Далі Буде'],[/ukrainefastdub/i,'UkraineFastDUB'],[/aniua/i,'AniUa'],[/vrdub/i,'VRdub'],[/jenary/i,'Jenary'],[/hatoshi/i,'Hatoshi'],[/білі\s+джин/i,'Білі Джин'],[/48\s*volts/i,'48 Volts'],[/amanogawa/i,'Amanogawa'],[/molfar/i,'Molfar'],[/adrian\s*zax/i,'Adrian Zax'],[/melodicvoice/i,'MelodicVoiceStudio'],[/espada/i,'Espada Studio'],[/lifecycle/i,'LifeCycle']];for(var i=0;i<tests.length;i++)if(tests[i][0].test(s))return tests[i][1];var p=String(x.group||'').split('›');var n=txt(p[p.length-1]||'');n=n.replace(/\b(озвучка|дубляж|українська|українською|ukr|dubbed?)\b/ig,'').replace(/[|•\-]+$/,'').trim();return n||'Українська'}
function isUkr(x){return variantScore(x)>0}
function groupEpisodes(a,season){var by={},nums=[];for(var i=0;i<a.length;i++){var x=a[i],xs=parseInt(x.season,10)||1;if(season!=null&&xs!==parseInt(season,10))continue;var n=parseInt(x.number,10);if(isNaN(n)||n<0)n=x.pos==null?i+1:x.pos;if(!by[n]){by[n]=[];nums.push(n)}var key=String(x.group||'')+'|'+String(x.file||''),dup=false;for(var j=0;j<by[n].length;j++)if(by[n][j]._key===key){dup=true;break}if(!dup){x._key=key;by[n].push(x)}}nums.sort(function(a,b){return a-b});for(var z=0;z<nums.length;z++)by[nums[z]].sort(function(a,b){var d=variantScore(b)-variantScore(a);if(d)return d;return String(a.group||'').localeCompare(String(b.group||''))});return{by:by,nums:nums}}
function uniqueStudios(list){var out=[],seen={};for(var i=0;i<list.length;i++){var x=list[i];if(!isUkr(x))continue;var name=studioName(x),key=name.toLowerCase();if(seen[key])continue;seen[key]=1;out.push({name:name,file:x.file,score:variantScore(x)})}if(!out.length&&list.length)out.push({name:'Українська',file:list[0].file,score:variantScore(list[0])});return out}
function intOr(v,d){var n=parseInt(v,10);return isNaN(n)?d:n}
function packEpisode(page,providerSeason,providerEpisode,displayEpisode){return'animeua:episode:'+encodeURIComponent(JSON.stringify({page:String(page||''),providerSeason:intOr(providerSeason,1),providerEpisode:intOr(providerEpisode,1),episode:intOr(displayEpisode,1)}))}
function unpackEpisode(token){try{return JSON.parse(decodeURIComponent(String(token||'').slice('animeua:episode:'.length)))}catch(e){return null}}
function playerSeasonHint(urls){var found=[];for(var i=0;i<urls.length;i++){try{var u=new URL(urls[i]),v=parseInt(u.searchParams.get('season'),10);if(v>0&&found.indexOf(v)<0)found.push(v)}catch(e){}}return found.length===1?found[0]:null}
function pageEpisodeCount(s){var t=txt(s||''),m=t.match(/Епізодів\s*:\s*(\d{1,4})/i);return m?parseInt(m[1],10):null}
function releaseEntries(entries,hint,count){var out=[],seen={};if(!Array.isArray(entries))return out;var seasons={};for(var i=0;i<entries.length;i++)seasons[intOr(entries[i].season,1)]=1;var genuineMulti=hint==null&&Object.keys(seasons).length>1;if(genuineMulti){for(var j=0;j<entries.length;j++){var x=entries[j],sn=intOr(x.season,1),ep=intOr(x.episode,null);if(ep==null||ep<0)continue;var k=sn+':'+ep;if(seen[k])continue;seen[k]=1;out.push({season:sn,providerSeason:sn,providerEpisode:ep,displayEpisode:ep})}return out}var positive=[];for(var q=0;q<entries.length;q++){var e=entries[q],ps=intOr(e.season,hint||1),pe=intOr(e.episode,null);if(pe==null||pe<=0)continue;var kk=ps+':'+pe;if(seen[kk])continue;seen[kk]=1;positive.push({season:1,providerSeason:ps,providerEpisode:pe})}var take=count&&count>0?Math.min(count,positive.length):positive.length;for(var z=0;z<take;z++){positive[z].displayEpisode=z+1;out.push(positive[z])}return out}
function uacdnProviderSeason(p,externalSeason){if(!p||!p.is_serial)return null;var se=p.seasons_episodes&&typeof p.seasons_episodes==='object'?p.seasons_episodes:null;if(!se)return intOr(p.season,1);var keys=Object.keys(se);if(externalSeason!=null&&se[String(externalSeason)])return intOr(externalSeason,1);var current=String(intOr(p.season,0));if(current!=='0'&&se[current])return intOr(current,1);if(keys.length===1)return intOr(keys[0],1);return externalSeason!=null?intOr(externalSeason,1):intOr(keys[0],1)}
function uacdnEpisodeEntries(p,externalSeason){var out=[],seen={};if(!p)return out;if(!p.is_serial)return[{season:1,episode:1}];var se=p.seasons_episodes&&typeof p.seasons_episodes==='object'?p.seasons_episodes:null;if(se){var ext=externalSeason!=null?intOr(externalSeason,1):null;if(ext!=null){var ps=uacdnProviderSeason(p,ext),a=se[String(ps)]||[];for(var i=0;i<a.length;i++){var n=intOr(a[i],null);if(n==null||n<0)continue;var key=ext+':'+n;if(!seen[key]){seen[key]=1;out.push({season:ext,episode:n})}}}else{var keys=Object.keys(se).sort(function(a,b){return intOr(a,0)-intOr(b,0)});for(var k=0;k<keys.length;k++){var sn=intOr(keys[k],1),arr=se[keys[k]]||[];for(var j=0;j<arr.length;j++){var ep=intOr(arr[j],null);if(ep==null||ep<0)continue;var kk=sn+':'+ep;if(!seen[kk]){seen[kk]=1;out.push({season:sn,episode:ep})}}}}}if(!out.length&&Array.isArray(p.episodes)){var s=externalSeason!=null?intOr(externalSeason,1):intOr(p.season,1);for(var q=0;q<p.episodes.length;q++){var e=intOr(p.episodes[q],null);if(e==null||e<0)continue;var k2=s+':'+e;if(!seen[k2]){seen[k2]=1;out.push({season:s,episode:e})}}}return out}
function ashdiEpisodeEntries(pf,externalSeason){if(!pf)return[];if(/^https?:\/\//i.test(pf))return[{season:externalSeason!=null?intOr(externalSeason,1):1,episode:1}];try{var a=[],cfg=JSON.parse(pf);flat(cfg,a,[],1);var out=[],seen={};for(var i=0;i<a.length;i++){var x=a[i],sn=intOr(x.season,1);if(externalSeason!=null&&sn!==intOr(externalSeason,1))continue;var ep=intOr(x.number,null);if(ep==null||ep<0)continue;var key=sn+':'+ep;if(!seen[key]){seen[key]=1;out.push({season:sn,episode:ep})}}out.sort(function(a,b){return a.season-b.season||a.episode-b.episode});return out}catch(e){return[]}}
async function load(url,cb){try{var s=await html(url);if(!s)return cb({success:false,error:'AnimeUA: сторінка недоступна.'});var h=s.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i),title=h?cleanTitle(h[1]):cleanTitle(meta(s,'og:title')||'AnimeUA'),poster=detailPoster(s),banner=detailBanner(s,poster),dm=s.match(/<div class=["'][^"']*page__text[^"']*["'][^>]*>([\s\S]*?)<\/div>/i),normalDesc=dm?txt(dm[1]):'',urls=iframeUrls(s,url).filter(usefulPlayer),hint=playerSeasonHint(urls),declared=pageEpisodeCount(s),raw=[],bestType='';for(var i=0;i<urls.length;i++){var cand=[];if(uacdnPlayer(urls[i])){var ud=await getUacdn(urls[i],url);cand=uacdnEpisodeEntries(ud.payload,hint)}else if(ashdiPlayer(urls[i])){var ad=await getAshdiFile(urls[i],url);cand=ashdiEpisodeEntries(ad.file,hint)}if(cand.length>raw.length){raw=cand;bestType=uacdnPlayer(urls[i])?'uacdn':'ashdi'}}if(!raw.length&&urls.length)raw=[{season:hint||1,episode:1}];var entries=releaseEntries(raw,hint,declared),eps=[],seen={};for(var z=0;z<entries.length;z++){var e=entries[z],key=e.season+':'+e.displayEpisode;if(seen[key])continue;seen[key]=1;eps.push(new Episode({name:'Серія '+e.displayEpisode,url:packEpisode(url,e.providerSeason,e.providerEpisode,e.displayEpisode),season:e.season,episode:e.displayEpisode,dubStatus:'dubbed',posterUrl:poster}))}console.log('[AnimeUA v47][LOAD] '+url+' players='+urls.length+' hint='+(hint==null?'all':hint)+' declared='+(declared==null?'?':declared)+' source='+bestType+' episodes='+eps.length);cb({success:true,data:new MultimediaItem({title:title,url:url,posterUrl:poster,bannerUrl:banner,type:'anime',description:normalDesc,episodes:eps})})}catch(e){console.log('[AnimeUA v47][LOAD FATAL] '+String(e));cb({success:false,error:'AnimeUA load: '+String(e)})}}
function normQuality(q,u){var s=String(q||'')+' '+String(u||'');if(/2160|4k|uhd/i.test(s))return'2160p';if(/1440/i.test(s))return'1440p';if(/1080|full\s*hd|fhd/i.test(s))return'1080p';if(/720|\bhd\b/i.test(s))return'720p';if(/480|\bsd\b/i.test(s))return'480p';if(/360/i.test(s))return'360p';return'Auto'}
function qualityRank(q){var m=String(q||'').match(/(2160|1440|1080|720|480|360)/);return m?parseInt(m[1],10):0}
function add(o,u,q,source,ref){var nq=normQuality(q,u),label=source||'AnimeUA';if(nq!=='Auto'&&label.toLowerCase().indexOf(nq.toLowerCase())<0)label+=' · '+nq;o.push(new StreamResult({url:dec(u),source:label,headers:{'Referer':ref||manifest.baseUrl+'/','User-Agent':UA}}))}
function addFile(o,file,source,ref){var r=dec(String(file||'').trim()),m,re=/\[([^\]]+)\](https?:\/\/[^,\s]+)/g,arr=[],seen={};while((m=re.exec(r))!==null){var u=dec(m[2]),q=normQuality(m[1],u);if(!seen[u]){seen[u]=1;arr.push({u:u,q:q})}}if(!arr.length&&/^https?:\/\//i.test(r))arr.push({u:r,q:normQuality('',r)});arr.sort(function(a,b){return qualityRank(b.q)-qualityRank(a.q)});for(var i=0;i<arr.length;i++)add(o,arr[i].u,arr[i].q,source,ref)}
function translationOk(t,ep){var n=String(t&&t.title||'');if(/субтит|\bsub\b|subbed/i.test(n))return false;var q=parseInt(t&&t.episodes_qty,10);return !q||ep==null||q>=Math.max(1,ep)}
async function uacdnFile(player,page,p,t,externalSeason,ep){try{var season=uacdnProviderSeason(p,externalSeason),body=JSON.stringify({id:parseInt(p.id,10)||0,translation:parseInt(t.id,10)||parseInt(p.translate,10)||0,season_number:p.is_serial?season:null,episode_number:p.is_serial?ep:null,force_cdn:String(p.force_cdn||''),turnstile_token:''}),api=new URL('/api/player/files',player).toString(),hs={'User-Agent':UA,'Accept':'application/json','Content-Type':'application/json','Referer':player,'Origin':new URL(player).origin},r=await http_post(api,hs,body),text=r&&typeof r.body==='string'?r.body:'';if(!text)return'';var j=JSON.parse(text);return String(j.file||'')}catch(e){console.log('[AnimeUA v47][UACDN API] '+String(e));return''}}
async function resolveUacdn(player,page,season,ep){var out=[],ud=await getUacdn(player,page),p=ud.payload;if(!p)return out;var tr=Array.isArray(p.translations)?p.translations.slice():[];if(!tr.length)tr=[{id:p.translate,title:p.translateTitle||'UA'}];tr.sort(function(a,b){var ad=parseInt(a.id,10)===parseInt(p.translate,10)?-1:0,bd=parseInt(b.id,10)===parseInt(p.translate,10)?-1:0;return ad-bd});var seen={};for(var i=0;i<tr.length;i++){var t=tr[i];if(!translationOk(t,ep))continue;var name=txt(t.title||p.translateTitle||'UA'),key=name.toLowerCase();if(seen[key])continue;seen[key]=1;var file=await uacdnFile(player,page,p,t,season,ep);if(file)addFile(out,file,name,player)}return out}
async function resolveAshdi(player,page,season,ep){var out=[],ad=await getAshdiFile(player,page),pf=ad.file;if(!pf)return out;if(/^https?:\/\//i.test(pf)){if(ep===1)addFile(out,pf,'AnimeUA',player);return out}try{var a=[],cfg=JSON.parse(pf);flat(cfg,a,[],1);var g=groupEpisodes(a,season),list=g.by[ep]||[],studios=uniqueStudios(list);if(!studios.length){var all=groupEpisodes(a),fallback=all.by[ep]||[];studios=uniqueStudios(fallback);if(studios.length)console.log('[AnimeUA v47][ASHDI FALLBACK] season='+season+' ep='+ep+' variants='+fallback.length)}for(var i=0;i<studios.length;i++)addFile(out,studios[i].file,studios[i].name,player)}catch(e){console.log('[AnimeUA v47][ASHDI PARSE] '+String(e))}return out}
async function resolveAshdiPage(player,page,ep){var out=[],ad=await getAshdiFile(player,page),pf=ad.file;if(!pf)return out;if(/^https?:\/\//i.test(pf)){if(ep===1)addFile(out,pf,'AnimeUA',player);return out}try{var a=[],cfg=JSON.parse(pf);flat(cfg,a,[],1);var g=groupEpisodes(a),studios=uniqueStudios(g.by[ep]||[]);for(var i=0;i<studios.length;i++)addFile(out,studios[i].file,studios[i].name,player)}catch(e){console.log('[AnimeUA v47][ASHDI PAGE] '+String(e))}return out}
async function loadStreams(url,cb){try{var token=String(url||'').trim();if(token.indexOf('animeua:episode:')!==0){var direct=[];addFile(direct,token,'AnimeUA',manifest.baseUrl+'/');return direct.length?cb({success:true,data:direct}):cb({success:false,error:'AnimeUA v46: невідомий формат епізоду.'})}var info=unpackEpisode(token);if(!info||!info.page)return cb({success:false,error:'AnimeUA v46: пошкоджений токен епізоду.'});var displayEp=intOr(info.episode,1),providerEp=info.providerEpisode!=null?intOr(info.providerEpisode,displayEp):displayEp,s=await html(info.page);if(!s)return cb({success:false,error:'AnimeUA v46: сторінка недоступна.'});var urls=iframeUrls(s,info.page).filter(usefulPlayer),hint=playerSeasonHint(urls),providerSeason=info.providerSeason!=null?intOr(info.providerSeason,hint||1):(info.season!=null?intOr(info.season,hint||1):(hint||1)),o=[];if(hint!=null){for(var a=0;a<urls.length&&!o.length;a++)if(ashdiPlayer(urls[a]))o=await resolveAshdiPage(urls[a],info.page,providerEp);for(var b=0;b<urls.length&&!o.length;b++)if(uacdnPlayer(urls[b]))o=await resolveUacdn(urls[b],info.page,providerSeason,providerEp)}else{for(var i=0;i<urls.length&&!o.length;i++)if(uacdnPlayer(urls[i]))o=await resolveUacdn(urls[i],info.page,providerSeason,providerEp);for(var j=0;j<urls.length&&!o.length;j++)if(ashdiPlayer(urls[j]))o=await resolveAshdi(urls[j],info.page,providerSeason,providerEp)}console.log('[AnimeUA v47][STREAMS] displayEp='+displayEp+' hint='+(hint==null?'all':hint)+' providerSeason='+providerSeason+' providerEp='+providerEp+' players='+urls.length+' streams='+o.length);if(!o.length)return cb({success:false,error:'AnimeUA v46: свіжі відеопотоки не знайдено.'});cb({success:true,data:o})}catch(e){console.log('[AnimeUA v47][STREAMS FATAL] '+String(e));cb({success:false,error:'AnimeUA v46 loadStreams: '+String(e)})}}
globalThis.getHome=getHome;globalThis.search=search;globalThis.load=load;globalThis.loadStreams=loadStreams;
}());