(function(){
var UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
var DESKTOP_UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/153.0.0.0 Safari/537.36';
var FALLBACK_IMAGE='https://raw.githubusercontent.com/arranoust/MiraiExt-SkyStream/main/banner.jpg';
function H(x){var h={'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Referer':manifest.baseUrl+'/'};if(x)for(var k in x)h[k]=x[k];return h}
function dec(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'").replace(/&nbsp;/g,' ')}
function abs(u){u=dec(u).trim();if(!u)return'';u=u.replace(/\\\//g,'/');if(u.indexOf('//')===0)return'https:'+u;if(/^https?:\/\//i.test(u))return u;if(u.charAt(0)==='/')return manifest.baseUrl.replace(/\/$/,'')+u;return manifest.baseUrl.replace(/\/$/,'')+'/'+u.replace(/^\.?\//,'')}
function txt(s){return dec(s).replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
async function html(u,h){var r=await http_get(u,h||H());return r&&typeof r.body==='string'?r.body:''}
async function getRaw(u,h){try{var r=await http_get(u,h||{}),b=r&&typeof r.body==='string'?r.body:'';return{body:b,status:r&&((r.statusCode||r.status))||0,error:''}}catch(e){return{body:'',status:0,error:String(e).slice(0,120)}}}
function meta(s,p){var r=new RegExp('<meta[^>]+property=["\\\']'+p+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),m=s.match(r);if(!m){r=new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+property=["\\\']'+p+'["\\\']','i');m=s.match(r)}return m?dec(m[1]):''}
function attr(tag,n){var r=new RegExp('(?:^|\\s)'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i'),m=String(tag||'').match(r);return m?m[2]:''}
function directPoster(u){u=abs(u);if(!u)return FALLBACK_IMAGE;try{var x=new URL(u);if(x.hostname==='animeua.club'||x.hostname==='www.animeua.club'){var sep=u.indexOf('?')>=0?'&':'?';return u+sep+'skystream=25'}}catch(e){}return u}
function validImage(u){return !!u&&!/no-img|placeholder|logo|avatar|icon/i.test(String(u))}
function bestSrcset(tag){var raw=attr(tag,'data-srcset')||attr(tag,'srcset');if(!raw)return'';var parts=raw.split(','),best='',score=-1;for(var i=0;i<parts.length;i++){var z=parts[i].trim().split(/\s+/),u=z[0]||'',d=z[1]||'',n=parseFloat(d)||i;if(/w$/i.test(d))n=parseFloat(d)||n;else if(/x$/i.test(d))n=(parseFloat(d)||1)*1000;if(validImage(u)&&n>=score){best=u;score=n}}return best}
function imageFromBlock(b){var tags=String(b||'').match(/<img\b[^>]*>/ig)||[];for(var i=0;i<tags.length;i++){var hi=bestSrcset(tags[i]);if(hi)return directPoster(hi);var names=['data-original','data-lazy-src','data-src','src'];for(var j=0;j<names.length;j++){var u=attr(tags[i],names[j]);if(validImage(u))return directPoster(u)}}return FALLBACK_IMAGE}
function detailPoster(s){var block=s.match(/<div[^>]*class=["'][^"']*pmovie__poster[^"']*["'][^>]*>[\s\S]*?<\/div>/i);if(block){var p=imageFromBlock(block[0]);if(p!==FALLBACK_IMAGE)return p}var og=meta(s,'og:image');if(validImage(og))return directPoster(og);var tags=s.match(/<img\b[^>]*>/ig)||[];for(var i=0;i<tags.length;i++){var hi=bestSrcset(tags[i]);if(hi)return directPoster(hi)}return FALLBACK_IMAGE}
function detailBanner(s,poster){var og=meta(s,'og:image');if(validImage(og)){var u=directPoster(og);if(u&&u!==poster)return u}var m=s.match(/(?:background-image\s*:\s*url\(|data-bg\s*=\s*["'])(https?:\/\/[^"')\s]+)/i);if(m&&validImage(m[1]))return directPoster(m[1]);return poster}
function cleanTitle(s){s=txt(s);return s.replace(/\s*[\/|–—-]\s*(дивитися|смотреть|аніме онлайн|anime online)[\s\S]*$/i,'').trim()||s}
function statusOf(block,openTag){var s=(String(openTag||'')+' '+String(block||'')).toLowerCase();if(/\bongoing\b|онґоїнґ|онгоінг/.test(s))return'ongoing';if(/\breleased\b|завершен|закінчен/.test(s))return'released';return''}
function cards(s){var out=[],seen={},re=/<a\b[^>]*class=(["\'])[^"\']*\bposter\b[^"\']*\bgrid-item\b[^"\']*\1[^>]*>[\s\S]*?<\/a>/gi,m;while((m=re.exec(s||''))){var b=m[0],ot=b.match(/^<a\b[^>]*>/i),u=abs(ot?attr(ot[0],'href'):''),t=b.match(/<h3\b[^>]*class=(["\'])[^"\']*\bposter__title\b[^"\']*\1[^>]*>([\s\S]*?)<\/h3>/i),title=t?txt(t[2]):txt(attr(ot?ot[0]:'','title')),image=imageFromBlock(b),status=statusOf(b,ot?ot[0]:'');if(!u||!title||seen[u])continue;seen[u]=1;out.push({title:title,url:u,image:image,status:status})}return out}
async function hydrate(list,limit){var out=[],n=limit?Math.min(list.length,limit):list.length;for(var i=0;i<n;i++){var x=list[i];out.push(new MultimediaItem({title:x.title,url:x.url,posterUrl:x.image||FALLBACK_IMAGE,type:'anime'}))}return out}
async function collectPages(basePath,pageCount){var all=[],seen={};for(var p=1;p<=pageCount;p++){try{var path=p===1?basePath:basePath.replace(/\/$/,'')+'/page/'+p+'/',u=abs(path),part=cards(await html(u));if(p>1&&!part.length)break;for(var i=0;i<part.length;i++){var x=part[i];if(!seen[x.url]){seen[x.url]=1;all.push(x)}}}catch(e){}}return all}
async function getHome(cb){try{var data={},main=await collectPages('/',2);if(!main.length)return cb({success:false,error:'AnimeUA: каталог не знайдено.'});data['🔥 Нове на AnimeUA']=await hydrate(main,40);var ongoing=main.filter(function(x){return x.status==='ongoing'});if(ongoing.length)data['🟢 Онґоїнґ']=await hydrate(ongoing,30);var filters=[['🎬 Повнометражки','/film/'],['📺 Аніме серіали','/anime/'],['ONA','/ona/'],['OVA','/ova/'],['💕 Романтика','/romantik/'],['🚀 Фантастика','/fantastika/'],['🧙 Фентезі','/fentezi/']];var jobs=[];for(var f=0;f<filters.length;f++)(function(spec){jobs.push((async function(){try{var list=await collectPages(spec[1],1);return list.length?{name:spec[0],items:await hydrate(list,24)}:null}catch(e){return null}})())})(filters[f]);var rows=await Promise.all(jobs);for(var i=0;i<rows.length;i++)if(rows[i])data[rows[i].name]=rows[i].items;cb({success:true,data:data})}catch(e){cb({success:false,error:'AnimeUA getHome: '+String(e)})}}
async function search(q,cb){try{var u=manifest.baseUrl+'/index.php?do=search&subaction=search&search_start=0&full_search=0&result_from=1&story='+encodeURIComponent(q),c=cards(await html(u));if(!c.length){var all=await collectPages('/',8),z=String(q||'').toLowerCase();c=all.filter(function(x){return x.title.toLowerCase().indexOf(z)>=0})}if(!c.length)return cb({success:false,error:'Нічого не знайдено.'});cb({success:true,data:await hydrate(c,50)})}catch(e){cb({success:false,error:'AnimeUA search: '+String(e)})}}
function playerFileValue(ph){var m=/\bfile\s*:/.exec(ph||'');if(!m)return null;var i=m.index+m[0].length,n=ph.length;while(i<n&&/\s/.test(ph.charAt(i)))i++;if(i>=n)return null;var q=ph.charAt(i);if(q==='"'||q==="'"||q==='`'){i++;var out='',esc=false;for(;i<n;i++){var c=ph.charAt(i);if(esc){out+=c;esc=false;continue}if(c==='\\'){esc=true;out+=c;continue}if(c===q)break;out+=c}return dec(out).replace(/\\(["'\/])/g,'$1')}if(q==='['){var start=i,depth=0,str='',esc2=false;for(;i<n;i++){var ch=ph.charAt(i);if(str){if(esc2){esc2=false;continue}if(ch==='\\'){esc2=true;continue}if(ch===str)str='';continue}if(ch==='"'||ch==="'"||ch==='`'){str=ch;continue}if(ch==='[')depth++;else if(ch===']'){depth--;if(depth===0)return dec(ph.slice(start,i+1))}}}var r=ph.slice(i).match(/^(https?:\/\/[^\s,}]+)/i);return r?dec(r[1]):null}
async function playerDebug(s,pageUrl){var d={iframe:false,player:false,file:false,playerLen:0,fileType:'none',error:'',status:0,attempt:0};try{var f=s.match(/<div[^>]*class=["'][^"']*video-inside[^"']*["'][^>]*>[\s\S]*?<iframe[^>]*(?:data-src|src)=["']([^"']+)["'][^>]*>/i)||s.match(/<iframe[^>]*(?:data-src|src)=["']([^"']+)["'][^>]*>/i);if(!f)return{file:null,debug:d};d.iframe=true;var pu=abs(f[1]),ph='',rr=await getRaw(pu,{});d.attempt=1;d.status=rr.status||0;if(rr.body){ph=rr.body}else{var relay='https://animeua-image-proxy.wholesale-source.workers.dev/player?page='+encodeURIComponent(pageUrl||manifest.baseUrl+'/');rr=await getRaw(relay,{});d.attempt=9;d.status=rr.status||0;if(rr.error)d.error=rr.error;if(rr.body)ph=rr.body}d.player=!!ph;d.playerLen=ph?ph.length:0;if(!ph)return{file:null,debug:d};var pf=playerFileValue(ph);d.file=!!pf;if(pf)d.fileType=/^https?:\/\//i.test(pf)?'url':(pf.charAt(0)==='['?'array':'other');return{file:pf,debug:d}}catch(e){d.error=String(e).slice(0,120);return{file:null,debug:d}}}
function episodeNumber(title,fallback){var s=txt(title||''),m=s.match(/(?:сер(?:ія|ии|ія)?|series?|episode|ep\.?)[^0-9]{0,8}0*(\d{1,3})/i);if(m)return parseInt(m[1],10);var nums=s.match(/\d{1,3}/g);if(nums&&nums.length)return parseInt(nums[nums.length-1],10);return fallback}
function flat(n,o,path,pos){path=path||[];if(!n)return;if(Array.isArray(n)){for(var i=0;i<n.length;i++)flat(n[i],o,path,i+1);return}if(typeof n!=='object')return;var title=txt(n.title||''),next=path;if(n.folder&&title)next=path.concat([title]);if(n.file){var k=episodeNumber(title,pos||1),group=path.join(' › ');o.push({title:title,number:k,file:dec(n.file),group:group,pos:pos||1})}if(n.folder)flat(n.folder,o,next,1)}
function variantScore(x){var s=String((x.group||'')+' '+(x.title||'')).toLowerCase(),v=0;if(/укр|ukr|україн|озвуч|дубляж|dubbed|дуб/.test(s))v+=120;if(/inari|didko|sundragon|sun dragon|робота голосом|рідний голос|ridnyi holos|ashdi|moonanime|togarashi|fanvox|далі буде|ukrainefastdub|aniua|vrdub|jenary|hatoshi|білі джин|48 volts|amanogawa|molfar|adrian zax|melodicvoice|lifecycle/.test(s))v+=90;if(/субтит|subbed|\bsub\b|original|оригінал|japan|jpn|japanese/.test(s))v-=160;return v}
function studioName(x){var s=txt((x.group||'')+' '+(x.title||''));var tests=[[/inari/i,'InariDuB'],[/didko/i,'Didko Studio'],[/sun\s*dragon|sundragon/i,'SunDragon Studio'],[/робота\s+голосом/i,'Робота Голосом'],[/рідний\s+голос|ridnyi\s+holos/i,'Рідний Голос'],[/ashdi/i,'ASHDI'],[/moonanime/i,'MOONANIME'],[/togarashi/i,'Togarashi'],[/fanvox/i,'FanVoxUA'],[/далі\s+буде/i,'Далі Буде'],[/ukrainefastdub/i,'UkraineFastDUB'],[/aniua/i,'AniUa'],[/vrdub/i,'VRdub'],[/jenary/i,'Jenary'],[/hatoshi/i,'Hatoshi'],[/білі\s+джин/i,'Білі Джин'],[/48\s*volts/i,'48 Volts'],[/amanogawa/i,'Amanogawa'],[/molfar/i,'Molfar'],[/adrian\s*zax/i,'Adrian Zax'],[/melodicvoice/i,'MelodicVoice'],[/lifecycle/i,'LifeCycle']];for(var i=0;i<tests.length;i++)if(tests[i][0].test(s))return tests[i][1];var p=String(x.group||'').split('›');var n=txt(p[p.length-1]||'');n=n.replace(/\b(озвучка|дубляж|українська|українською|ukr|dubbed?)\b/ig,'').replace(/[|•\-]+$/,'').trim();return n||'Українська'}
function isUkr(x){return variantScore(x)>0}
function groupEpisodes(a){var by={},nums=[];for(var i=0;i<a.length;i++){var x=a[i],n=parseInt(x.number,10);if(isNaN(n)||n<1)n=x.pos||i+1;if(!by[n]){by[n]=[];nums.push(n)}var key=String(x.group||'')+'|'+String(x.file||''),dup=false;for(var j=0;j<by[n].length;j++)if(by[n][j]._key===key){dup=true;break}if(!dup){x._key=key;by[n].push(x)}}nums.sort(function(a,b){return a-b});for(var z=0;z<nums.length;z++)by[nums[z]].sort(function(a,b){var d=variantScore(b)-variantScore(a);if(d)return d;return String(a.group||'').localeCompare(String(b.group||''))});return{by:by,nums:nums}}
function uniqueStudios(list){var out=[],seen={};for(var i=0;i<list.length;i++){var x=list[i];if(!isUkr(x))continue;var name=studioName(x),key=name.toLowerCase();if(seen[key])continue;seen[key]=1;out.push({name:name,file:x.file,score:variantScore(x)})}if(!out.length&&list.length)out.push({name:'Українська',file:list[0].file,score:variantScore(list[0])});return out}
function packStudios(list){return'animeua:studios:'+encodeURIComponent(JSON.stringify(list))}
async function load(url,cb){try{var s=await html(url);if(!s)return cb({success:false,error:'AnimeUA: сторінка недоступна.'});var h=s.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i),title=h?cleanTitle(h[1]):cleanTitle(meta(s,'og:title')||'AnimeUA'),poster=detailPoster(s),banner=detailBanner(s,poster),dm=s.match(/<div class=["'][^"']*page__text[^"']*["'][^>]*>([\s\S]*?)<\/div>/i),normalDesc=dm?txt(dm[1]):'',eps=[],pd=await playerDebug(s,url),pf=pd.file;if(pf){if(/^https?:\/\//i.test(pf)){eps.push(new Episode({name:'Серія 1',url:pf,season:1,episode:1,dubStatus:'dubbed',posterUrl:poster}))}else try{var a=[],cfg=JSON.parse(pf);flat(cfg,a,[],1);var g=groupEpisodes(a);for(var i=0;i<g.nums.length;i++){var n=g.nums[i],studios=uniqueStudios(g.by[n]);if(!studios.length)continue;eps.push(new Episode({name:'Серія '+n,url:packStudios(studios),season:1,episode:n,dubStatus:'dubbed',posterUrl:poster}))}}catch(e){}}cb({success:true,data:new MultimediaItem({title:title,url:url,posterUrl:poster,bannerUrl:banner,type:'anime',description:normalDesc,episodes:eps})})}catch(e){cb({success:false,error:'AnimeUA load: '+String(e)})}}
function normQuality(q,u){var s=String(q||'')+' '+String(u||'');if(/2160|4k|uhd/i.test(s))return'2160p';if(/1440/i.test(s))return'1440p';if(/1080|full\s*hd|fhd/i.test(s))return'1080p';if(/720|\bhd\b/i.test(s))return'720p';if(/480|\bsd\b/i.test(s))return'480p';if(/360/i.test(s))return'360p';return'Auto'}
function qualityRank(q){var m=String(q||'').match(/(2160|1440|1080|720|480|360)/);return m?parseInt(m[1],10):0}
function add(o,u,q,source){var nq=normQuality(q,u);o.push(new StreamResult({url:dec(u),quality:nq,source:source||'AnimeUA',headers:{'Referer':manifest.baseUrl+'/','User-Agent':UA}}))}
function addFile(o,file,source){var r=dec(String(file||'').trim()),m,re=/\[([^\]]+)\](https?:\/\/[^,\s]+)/g,arr=[],seen={};while((m=re.exec(r))!==null){var u=dec(m[2]),q=normQuality(m[1],u);if(!seen[u]){seen[u]=1;arr.push({u:u,q:q})}}if(!arr.length&&/^https?:\/\//i.test(r))arr.push({u:r,q:normQuality('',r)});arr.sort(function(a,b){return qualityRank(b.q)-qualityRank(a.q)});for(var i=0;i<arr.length;i++)add(o,arr[i].u,arr[i].q,source)}
async function loadStreams(url,cb){try{var o=[],r=String(url||'').trim();if(r.indexOf('animeua:studios:')===0){var raw=decodeURIComponent(r.slice('animeua:studios:'.length)),studios=JSON.parse(raw);for(var i=0;i<studios.length;i++)addFile(o,studios[i].file,studios[i].name)}else addFile(o,r,'AnimeUA');if(!o.length)return cb({success:false,error:'AnimeUA: відеопотік не знайдено.'});cb({success:true,data:o})}catch(e){cb({success:false,error:'AnimeUA loadStreams: '+String(e)})}}
globalThis.getHome=getHome;globalThis.search=search;globalThis.load=load;globalThis.loadStreams=loadStreams;
}());